FROM ubuntu
MAINTAINER sandeep
RUN  mkdir dockerpractice
USER root
RUN apt-get update -y
RUN apt-get install -y curl unzip wget
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install
RUN curl "mcr.microsoft.com/azure-cli"
RUN curl "https://github.com/docker/releases/download"  
RUN apt-get update -y
   


